### ISSUE TITLE
certificate generation failure

### ISSUE THREAD

**Issue by dnadeau4** [cedadev/MyProxyClient#11]
Following this issue
https://github.com/philipkershaw/MyProxyClient/issues/8

I cloned `master` in `github` and installed the software.  `myproxyclient` failed to generate a certificate.

For pip I used version 2.0.1 and then I also tried with conda version 2.0.1.  Both worked fine with my server (esgf-node.llnl.gov)

**Comment by philipkershaw** [comment]
Hi Denis,

Sorry for the slow response.  2.0.1 had a change to use sha256 for cert signing but this will be in master also.  Which version of Python are you using?  It may also be worth checking against the current devel

**Comment by dnadeau4** [comment]
I was using python `2.7`, but our tests are on `OSX` and `Linux` for `python2` and `python3`.  I have created a `myproxyclient` package temporarily in our nightly channel.  

Our `CDMS` package tests use `myproxyclient` to retrieve credential and open file from `ESGF` seamlessly.   We use `OpeNDAP` URLs and read the data without downloading the files.  

We get `myproxyclient` from `conda-forge` but maybe we should get it from `pip`.
