### ISSUE TITLE
MYPROXY_SERVER_DN does not work with Python 2

### ISSUE THREAD

**Issue by lukaszlacinski** [cedadev/MyProxyClient#12]
myproxy/client.py

        if six.PY3:
            cert_dn_list.sort()
            self.__certDN = [(bytes(i[0], 'utf-8'), bytes(i[1],'utf-8'))
                             for i in cert_dn_list]
        else:
            self.__certDN = cert_dn_list.sort()

sets self.__certDN to None because cert_dn_list.sort() returns None. It should be:

        cert_dn_list.sort()
        if six.PY3:
            self.__certDN = [(bytes(i[0], 'utf-8'), bytes(i[1],'utf-8'))
                             for i in cert_dn_list]
        else:
            self.__certDN = cert_dn_list

**Comment by philipkershaw** [comment]
Fixed in `devel` now: https://github.com/cedadev/MyProxyClient/blob/devel/myproxy/client.py#L195

Can you give it a try and confirm?

**Comment by lukaszlacinski** [comment]
Tried the devel branch. MYPROXY_SERVER_DN works with Python 2.x now.
