### ISSUE TITLE
Logon fails after recent update of ESGF nodes

### ISSUE THREAD

**Issue by cehbrecht** [cedadev/MyProxyClient#14]
Logon with the latest https://github.com/ESGF/esgf-pyclient fails with the following error message:

`Error: [('SSL routines', 'SSL3_GET_RECORD', 'wrong version number')]`

@soay got it working with the following patch in `myproxyclient`:

```
In File
../lib/python2.7/site-packages/myproxy/client.py

change Line 356:

SSL_METHOD = SSL.TLSv1_METHOD
to
SSL_METHOD = SSL.SSLv23_METHOD
```

**Comment by philipkershaw** [comment]
SSL is insecure and deprecated!  The server-side config for the respective MyProxy instances will need to be updated.  Don't tell me it includes CEDA's! :)

**Comment by cehbrecht** [comment]
@philipkershaw ... this means the ESGF server installation needs to be fixed and not the client? What would you recommend in the meantime?

**Comment by philipkershaw** [comment]
I would monkey patch the client if you have to.  Server-side configurations need to be fixed.

**Comment by cehbrecht** [comment]
@philipkershaw ok. thanks.

**Comment by dnadeau4** [comment]
We have that issue as well,  I hacked myproxclient like you did, but I am trying to find a more stable solution.   

Do you think changing this ESGF configuration will work across the board?

https://github.com/cedadev/esgf-docker/blob/master/proxy/conf/esgf.conf#L56

From:

`ssl_protocols TLSv1 TLSv1.1 TLSv1.2;`

To:
`ssl_protocols TLSv1.2;`

@sashakames

**Comment by sashakames** [comment]
That's for apache.  Still looking for a comparable myproxy setting.  Complementary to this, the pssht tool can scan ports, so will investigate that too to see what myproxy is doing.

**Comment by dnadeau4** [comment]
Thanks!
