### ISSUE TITLE
conda-forge build fails ... six missing in requirements

### ISSUE THREAD

**Issue by cehbrecht** [cedadev/MyProxyClient#16]
I was looking at conda-forge with automatic package build after pypi update:
https://github.com/conda-forge/myproxyclient-feedstock/pulls

It is missing `six` in the requirements.

**Comment by cehbrecht** [comment]
See https://github.com/conda-forge/myproxyclient-feedstock/issues/4

**Comment by valeriupredoi** [comment]
@cehbrecht let's get #20 merged, then I can take care of building us a new PyPI package, and will get the conda-forge release too, based on the new PyPI package (now that I am a maintainer there too) - would you be able to do a quick review of #20 pls? :beer:

**Comment by valeriupredoi** [comment]
@cehbrecht I just popped a new v2.1.1 on conda forge, Python 3.12-supported too https://anaconda.org/conda-forge/myproxyclient - all good with the pkg build etc, happy days :grin:

**Comment by valeriupredoi** [comment]
closing this now, after five years (the stereotypical where do you see yourself in five years' time question haha)
