### ISSUE TITLE
Python 3.0-3.4 not supported

### ISSUE THREAD

**Issue by lukaszlacinski** [cedadev/MyProxyClient#17]
MyProxyClient does not work with Python 3.0-3.4 because the string formatting operator % in Python 3.0-3.4 does not support bytes operands. It causes errors:
```
  File "/tmp/venv3/lib64/python3.4/site-packages/myproxy/client/__init__.py", line 1511, in logon
    lifetime)
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'
```
If the following code:
```
    GET_CMD=b"""VERSION=MYPROXYv2
COMMAND=0
USERNAME=%s
PASSPHRASE=%s
LIFETIME=%d"""
<snap>
        cmd = self.GET_CMD % (_string2bytes(userid),
                              _string2bytes(passphrase),
                              lifetime)

        conn.write(cmd)
```
is replaced by
```
    GET_CMD="""VERSION=MYPROXYv2
COMMAND=0
USERNAME=%s
PASSPHRASE=%s
LIFETIME=%d"""
<snap>
        cmd = self.GET_CMD % (userid, passphrase, lifetime)
        conn.write(cmd.encode())
```
MyProxyClient (the GET command) will work with Python 2.6, 2.7 and 3.x.

**Comment by valeriupredoi** [comment]
Hi @lukaszlacinski we will not support Pythons <3.9, sorry (I guess, given the age of this issue, you won't even need such old Pythons anyway anymore, but please do let me know if you still need them, I'll see what I can do in the future - for now, the upcoming version 2.1.1 will only support Pythons 3.9-3.12 inclusive). Cheers :beer:
